import type { CharacterProfile } from '../types';

export const profile: CharacterProfile = {
  name: 'Asher',
  emotionalBaseline: {
    joy: 25,
    sadness: 45,
    anger: 40,
    fear: 45,
    disgust: 40,
    surprise: 35,
    trust: 40,
    anticipation: 55,
  },
  temperament: {
    patience: 45,
    impulsiveness: 35,
    confrontationalTendency: 45,
    agreeableness: 40,
    emotionalContainment: 55,
    riskAppetite: 50,
    curiosity: 45,
    prideSensitivity: 55,
    shameSensitivity: 50,
    empathyBaseline: 45,
    dominanceVsDeference: 40,
    adaptabilityVsRigidity: 50,
  },
  moralStructure: {
    primaryDriver: 'Pragmatic survival and escape from his father\'s shadow; self-determination at the cost of relationships',
    moralRigidity: 35,
    guiltSensitivity: 55,
    justificationTendency: 55,
  },
  presentInChapters: [1, 2, 3],
  reasoning: {
    'emotionalBaseline.joy': 'Low joy sensitivity. Asher\'s rare moments of lightness are subdued: his "easy confidence more subdued than usual" after passing the test (Ch1). As a child, he smiled at Praew and Haldric\'s boldness about his father (Ch3). Joy is muted by the weight he carries.',
    'emotionalBaseline.sadness': 'Moderate sadness sensitivity. He feels the weight of betraying his friends: "I\'m sorry, Haldric. Praew" (Ch2 internal). He looked "torn" before choosing the stones over Haldric (Ch1). His sadness manifests as quiet withdrawal rather than tears.',
    'emotionalBaseline.anger': 'Moderate anger sensitivity. Confronts his father coldly: "You should know better than to call me that in public" (Ch2). As a child, he yells back at Arthur: "Or are you too busy hiding down here like a coward?" (Ch3). His anger is controlled and cutting, not explosive.',
    'emotionalBaseline.fear': 'Moderate fear sensitivity. Terrified on the surface: "I can\'t see! What\'s happening!?" (Ch2). Nervous before Azel. But he pushes through fear consistently. His fear of becoming like his father is his deepest psychological driver.',
    'emotionalBaseline.disgust': 'Moderate. Disgusted by his father\'s control and manipulations (Ch2-3). "Hated being in that bolting man\'s shadow" (Ch3). His disgust is directed at power abuse and hypocrisy rather than physical stimuli.',
    'emotionalBaseline.surprise': 'Low-moderate. He\'s caught off guard by the surface\'s blinding light (Ch2) and Renwick\'s insight about "all Rivers run cold" (Ch2). But he\'s generally composed and anticipates situations.',
    'emotionalBaseline.trust': 'Moderate trust sensitivity. He trusted Praew and Haldric deeply as childhood friends, making his betrayal more painful for all. His trust in others is guarded due to his father\'s controlling nature. Renwick\'s "All Rivers run cold" hits because he fears it\'s true.',
    'emotionalBaseline.anticipation': 'Moderate-high anticipation. He planned to become a Hunter for twelve years specifically to escape his father. He reads the test situation and makes a calculated choice. He\'s always thinking about the future implications of his actions.',

    'temperament.patience': 'Moderate patience. He endures years under his father\'s control, waits twelve years to take the Hunter test. He\'s patient in pursuit of long-term goals. But he\'s impatient with people who waste his time (snaps at Renwick Ch2).',
    'temperament.impulsiveness': 'Low-moderate impulsiveness. His betrayal of Haldric looks impulsive but was actually a split-second calculation: "Asher realized the ploy — they were both about to fail" (Ch3). He acts decisively but with reason, not pure impulse.',
    'temperament.confrontationalTendency': 'Moderate. He confronts his father directly (Ch2, Ch3) but walks away from Haldric and Praew without explanation — avoiding emotional confrontation while engaging in ideological ones. Selective confrontation.',
    'temperament.agreeableness': 'Low-moderate. He defends Praew against Renwick (Ch1) showing care, but ultimately prioritizes self-interest (taking both stones Ch1). He\'s agreeable when it costs nothing, pragmatic when it matters.',
    'temperament.emotionalContainment': 'Moderate-high containment. "His hands were trembling at his sides" but he doesn\'t react externally to being named Beast Hunter (Ch2). He doesn\'t cry when leaving friends. He swallows his guilt internally. Better contained than Haldric but not as locked down as The Prime.',
    'temperament.riskAppetite': 'Moderate. He takes the enormous risk of becoming a Hunter against his father\'s wishes. But his betrayal was actually risk-averse: he chose the certain outcome (both stones) over the uncertain one (both might fail). His risk calculation is pragmatic.',
    'temperament.curiosity': 'Moderate. He\'s curious about the surface world, asks questions about the food shortage (Ch3), wants to understand why beasts can be farmed. His curiosity is practical rather than investigative.',
    'temperament.prideSensitivity': 'Moderate-high. He hates being in his father\'s shadow: "he just wanted to be seen for himself" (Ch3). His voice deepens when introducing himself (Ch3). Being "The Prime\'s son" is a wound to his pride and identity.',
    'temperament.shameSensitivity': 'Moderate. He feels shame about his family name ("All Rivers run cold" stings Ch2), about the betrayal he committed, and about his father\'s reputation. "That bolting Ratrod. Though... he\'s right, isn\'t he?" (Ch2 about Renwick\'s cold accusation).',
    'temperament.empathyBaseline': 'Moderate empathy. He cares about Praew and Haldric (the childhood friendship was genuine). He\'s affected by Renwick\'s harassment of Praew (Ch1). But he suppresses empathy when it conflicts with survival, making him capable of the betrayal.',
    'temperament.dominanceVsDeference': 'Moderate-deferential. He defers to Azel immediately (Ch2-3), follows Hunter Steel\'s orders. His rebellion against his father is actually about autonomy rather than dominance — he wants to be free, not to rule.',
    'temperament.adaptabilityVsRigidity': 'Moderate adaptability. He adapts to surface life, to Azel\'s authority, to his new role. But his core decision (escape father, become Hunter) is rigid — he won\'t compromise on it even at the cost of his closest friendships.',

    'moralStructure.primaryDriver': 'Self-determination and pragmatic survival. Asher\'s primary drive is escaping his father\'s shadow and forging his own path. He chose betrayal not from malice but from a calculated assessment that both would fail otherwise. "A Hunter mustn\'t hesitate" (Ch2-3).',
    'moralStructure.moralRigidity': 'Low moral rigidity. He operates on situational ethics. The betrayal shows he\'ll break moral rules (loyalty to friends) when the situation demands pragmatic action. He doesn\'t have rigid principles — he adapts his morality to circumstances.',
    'moralStructure.guiltSensitivity': 'Moderate-high guilt. "I\'m sorry, Haldric. Praew" echoes internally (Ch2). He can\'t meet their eyes after the betrayal. He walks away without saying goodbye because he can\'t face what he\'s done. Guilt lingers persistently but doesn\'t change his course of action.',
    'moralStructure.justificationTendency': 'Moderate-high. He rationalizes the betrayal: his father was sabotaging them both, at least one of them made it. "A Hunter mustn\'t hesitate" becomes his mantra (Ch2-3). He uses logic to justify emotional damage, but the justifications feel hollow even to him.',
  },
};
