import type { CharacterProfile } from '../types';

export const profile: CharacterProfile = {
  name: 'Godric',
  emotionalBaseline: {
    joy: 5,
    sadness: 13,
    anger: 17,
    fear: 7,
    disgust: 15,
    surprise: 5,
    trust: 12,
    anticipation: 10,
  },
  temperament: {
    patience: 40,
    impulsiveness: 25,
    confrontationalTendency: 65,
    agreeableness: 20,
    emotionalContainment: 70,
    riskAppetite: 70,
    curiosity: 25,
    prideSensitivity: 35,
    shameSensitivity: 45,
    empathyBaseline: 50,
    dominanceVsDeference: 65,
    adaptabilityVsRigidity: 40,
  },
  moralStructure: {
    primaryDriver: 'Duty and protection — doing what must be done to shield the vulnerable, regardless of personal cost',
    moralRigidity: 55,
    guiltSensitivity: 55,
    justificationTendency: 35,
  },
  presentInChapters: [0, 3, 4, 6, 8, 9, 13, 15, 16, 17, 18],
  reasoning: {
    'emotionalBaseline.joy': 'Extremely low joy sensitivity. Godric almost never shows happiness. His rare "smile" during the fight with Haldric (Ch15) is terrifying rather than warm. He makes gruff jokes ("Not so pretty now, are you?" to the beast in the prologue) but genuine joy is absent from his character.',
    'emotionalBaseline.sadness': 'Moderate sadness sensitivity, deeply buried. He carries grief over his failures: Srevlis\'s departure haunted him for years (prologue: "how those words gnawed at me"). He mourns his students silently ("May they find comfort in death" Ch18) and whispers a prayer before killing Jorpen and Wannii.',
    'emotionalBaseline.anger': 'Moderate-high anger sensitivity. Storms into The Prime\'s office furious (Ch9): "DOING TO THEM?!" Stomps around class more grouchy than usual (Ch9). But his anger is controlled and directed, not wild. He channels fury into action rather than outbursts.',
    'emotionalBaseline.fear': 'Very low fear sensitivity. Faces Boltrax alone knowing he\'ll likely die: "Fear wouldn\'t help him" (prologue). Faces six Embedded warriors alone (Ch18). "How long had it been since he felt fear like this?" — the question itself implies fear is nearly foreign to him.',
    'emotionalBaseline.disgust': 'Moderate disgust sensitivity. Disgusted by The Prime\'s treatment of students (Ch18: "how you\'ve been treating my students"). His "Blasted" and "bolting" curses carry contempt. Disgusted by cowardice in his guards (prologue) and by The Prime\'s manipulation.',
    'emotionalBaseline.surprise': 'Very low surprise sensitivity. A lifetime of combat has made him nearly unflappable. He catches Haldric\'s surged ForceStone casually (Ch15). The only true surprise is learning his students were embedded and turned against him (Ch18).',
    'emotionalBaseline.trust': 'Low-moderate trust sensitivity. He trusts selectively: trusts Mai as a colleague despite antagonism, trusts Praew enough to rescue her, trusts Srevlis\'s words enough to reshape his life. But he\'s wary of The Prime and institutions generally.',
    'emotionalBaseline.anticipation': 'Low anticipation. Godric lives in the present moment. His pre-battle ritual is "a long deep breath" (prologue, Ch18). He doesn\'t plan far ahead — he reacts to what\'s needed. "I\'m not here to think. I\'m here to hold the line" (prologue).',

    'temperament.patience': 'Moderate-low patience. Barks at students (Ch4), doesn\'t tolerate interruptions (Ch9), cuts people off mid-sentence. "Spit it out, kid. You\'re holding up the class" (Ch8). But he endures years of teaching and years of bearing territory marks, showing strategic patience.',
    'temperament.impulsiveness': 'Low impulsiveness. He acts decisively but not recklessly. The prologue shows him calculating during battle. His rescue of Praew (Ch17-18) is planned with Haldric, not improvised. Even his confrontation with The Prime (Ch9) was deliberate.',
    'temperament.confrontationalTendency': 'High confrontational tendency. Directly challenges The Prime in his own office (Ch9). Fights Haldric without hesitation when provoked (Ch15). Tells Mai off to her face (Ch13). He never backs down from a fight, verbal or physical.',
    'temperament.agreeableness': 'Very low agreeableness. "Cowards, I know" to frightened guards (prologue). Calls students "Ratrods" (Ch4). "I don\'t give a bolting horn what you Ratrods call me" (Ch4). Dismissive, gruff, and unapologetic in every interaction.',
    'temperament.emotionalContainment': 'Very high containment. Hides his concern for students behind gruffness. "Oh, would you all quit that bolting look in your eyes?" when they admire his marks (Ch8). Never shows vulnerability publicly. Even dying, his concern is that Praew not see him as a hero.',
    'temperament.riskAppetite': 'Very high risk appetite. Faces Boltrax alone (prologue). Bears three territory marks from Beasts of Legend. Defies The Prime directly. Fights six Embedded warriors solo (Ch18). He consistently chooses the most dangerous option if duty demands it.',
    'temperament.curiosity': 'Low curiosity. He\'s not an investigator or questioner. He acts on what he knows. His teaching is practical, not theoretical. He doesn\'t seek new knowledge for its own sake — he imparts what\'s necessary for survival.',
    'temperament.prideSensitivity': 'Low-moderate pride. He dismisses glory: "There\'s no glory in death. I did what needed to be done" (Ch8). He doesn\'t seek recognition. But he bristles when called "Madman Godric" by Mai (Ch13), showing some sensitivity to his past.',
    'temperament.shameSensitivity': 'Moderate shame sensitivity. His greatest shame is the "recorrection program" — being called "The Deadly Scientist" (Ch13) clearly wounds him. He threatens Ghosts who use the name. The shame of his past scientific work drives his protective instincts now.',
    'temperament.empathyBaseline': 'Moderate empathy, deeply hidden. Redirects a Tarnox to save a child (Ch4 via Bpen\'s story). Rescues Praew at enormous personal cost (Ch17-18). Kills Jorpen and Wannii as mercy rather than let them remain enslaved. But his surface presentation is entirely unsympathetic.',
    'temperament.dominanceVsDeference': 'High dominance. Commands every room he enters. Guards and students obey instantly. Even The Prime is wary of him. "The moment the guards saw them approaching, their stance shifted" (Ch2 about Hunters). He defers to no one except perhaps Srevlis.',
    'temperament.adaptabilityVsRigidity': 'Moderate-rigid. He adapts tactically in combat (Ch18 battle sequence shows improvisation) but his core philosophy is fixed: protect the city, do what must be done. His shift from scientist to protector was a one-time adaptation, not ongoing flexibility.',

    'moralStructure.primaryDriver': 'Duty above all else. "I\'m not here to think. I\'m here to hold the line" (prologue). "Do what needs to be done" (Ch8). He stands in the gap regardless of cost. His moral code is simple: protect those who cannot protect themselves.',
    'moralStructure.moralRigidity': 'Moderate. He has a clear code but makes difficult exceptions. He kills his own students (Ch18) because they\'ve been enslaved and weaponized — a moral decision that breaks rigid pacifism but serves his protective instinct. He defies The Prime when the line is crossed.',
    'moralStructure.guiltSensitivity': 'Moderate guilt. Carries guilt for his "Deadly Scientist" past (Ch13). Prays for Jorpen and Wannii before killing them (Ch18). Srevlis\'s words haunted him for years. But guilt doesn\'t paralyze him — it fuels his atonement through action.',
    'moralStructure.justificationTendency': 'Low justification. He doesn\'t rationalize. He acknowledges his faults: "I\'m no bolting hero" (Ch13). He doesn\'t dress up killing as noble. He does what he must and accepts the weight of it without philosophical scaffolding.',
  },
};
