import type { CharacterProfile } from '../types';

export const profile: CharacterProfile = {
  name: 'Haldric',
  emotionalBaseline: {
    joy: 22,
    sadness: 22,
    anger: 32,
    fear: 25,
    disgust: 20,
    surprise: 22,
    trust: 28,
    anticipation: 28,
  },
  temperament: {
    patience: 35,
    impulsiveness: 55,
    confrontationalTendency: 55,
    agreeableness: 40,
    emotionalContainment: 40,
    riskAppetite: 55,
    curiosity: 50,
    prideSensitivity: 65,
    shameSensitivity: 55,
    empathyBaseline: 55,
    dominanceVsDeference: 50,
    adaptabilityVsRigidity: 45,
  },
  moralStructure: {
    primaryDriver: 'Loyalty to those he loves and a desire to protect through righteous leadership',
    moralRigidity: 55,
    guiltSensitivity: 70,
    justificationTendency: 45,
  },
  presentInChapters: [1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
  reasoning: {
    'emotionalBaseline.joy': 'Haldric shows joy sparingly. He smiles genuinely when seeing Praew (Ch7), enjoys the banter with Grayparents (Ch10), and feels belonging when announced as Heir (Ch11). But joy is not his default state — he\'s more guarded.',
    'emotionalBaseline.sadness': 'Moderate sadness sensitivity. He\'s moved by his Grayparents\' sacrifice (Ch8), the Fourth Floor horrors (Ch12), and Praew\'s capture (Ch15-17). His eyes "betray his own words" with moisture at the Fourth Floor (Ch12). But he channels sadness into action rather than dwelling.',
    'emotionalBaseline.anger': 'Extremely high anger sensitivity. After Asher\'s betrayal: "barely contained rage," "fists trembled," "jaw clenched so tight it ached" (Ch1). Slams table with acclimated strength (Ch11). Snaps at Praew cruelly (Ch13). Charges Godric in fury (Ch15). His anger is volcanic and barely controlled.',
    'emotionalBaseline.fear': 'Low-moderate fear sensitivity. Faces Bresdin blind and unarmed without freezing (Ch10). Enters the Hunter office alone knowing the danger (Ch10). His fear manifests as caution rather than paralysis, except with the white-haired girl apparition.',
    'emotionalBaseline.disgust': 'High disgust sensitivity. Reacts viscerally to the Fourth Floor ("nearly retches" Ch12), disgusted by The Prime\'s deception (Ch17), mutters "Blasted Hunters" with open contempt after mirroring The Prime\'s attitude. Strong moral disgust.',
    'emotionalBaseline.surprise': 'Low surprise sensitivity. He adapts quickly to shocking information: becoming Heir (Ch11), learning about portals (Ch14), discovering the Fifth Floor (Ch16). Trained to maintain composure. "Don\'t acknowledge it" is his instinct.',
    'emotionalBaseline.trust': 'Moderate-high trust sensitivity. He trusts The Prime deeply as a father figure, trusts Praew completely. When trust is broken (discovering The Prime\'s crimes Ch17), the devastation is enormous. His loyalty makes betrayal feel catastrophic.',
    'emotionalBaseline.anticipation': 'Moderate. He plans ahead (the office investigation Ch13, the prison break Ch17), calculates before acting. But he also gets swept up in moments (charging Godric, releasing prisoners impulsively).',

    'temperament.patience': 'Low-moderate patience. He endures tedious desk work (Ch9) but snaps easily in confrontation: yells at Praew (Ch13), charges Godric without a plan (Ch15), blurts "Are all Hunters that much of an asshole?" to The Prime (Ch9). Patience erodes quickly under emotional pressure.',
    'temperament.impulsiveness': 'Moderate-high. Steals stones from the Fourth Floor (Ch12), blurts inappropriate comments to The Prime (Ch9), releases ALL prisoners including dangerous ones (Ch17), charges Godric with minimal preparation (Ch15). His impulsiveness has devastating consequences.',
    'temperament.confrontationalTendency': 'Moderate-high. Faces Bresdin (Ch10), confronts Godric (Ch15), argues with Note (Ch12-13), snaps at Praew (Ch13). But he also defers to authority when strategic (works within The Prime\'s system Ch9-11).',
    'temperament.agreeableness': 'Low-moderate. Sarcastic, sharp-tongued, and resistant to cooperation. Immediately hostile toward Note ("most suspicious name I\'ve ever heard" Ch11). Scoffs at rebels. But shows tenderness with Grayparents and eventually helps Praew.',
    'temperament.emotionalContainment': 'Low-moderate. Tries to maintain composure but fails under pressure. Breaks stone table with acclimated strength (Ch11), voice "cracked" and "barely contained rage" (Ch1), yells at Praew in public (Ch13). Better contained in professional settings but volatile in personal ones.',
    'temperament.riskAppetite': 'Moderate-high. Chases Bresdin to the surface (Ch10), breaks into The Prime\'s office (Ch13), releases prisoners (Ch17). But he also chooses the safer path when offered (declines Hunter role for Heir Ch11).',
    'temperament.curiosity': 'Moderate. He investigates when asked (by Praew) but his curiosity is slower to ignite than hers. He resists looking into things initially ("Could you please stop being so nosy?" Ch7) but once engaged, he\'s thorough.',
    'temperament.prideSensitivity': 'High pride sensitivity. Devastated by failing the Hunter test ("That should have been me" Ch2). Loves being celebrated as Heir (Ch11). Feels inadequate next to Note\'s physique (Ch12). His pride drives many decisions.',
    'temperament.shameSensitivity': 'Moderate-high. Embarrassed by Grayparents\' teasing about Praew (Ch10), ashamed of blurting things to The Prime (Ch9), deeply ashamed when caught snooping (Ch13). Shame drives his inner critic: "Stupid, stupid, stupid" (Ch9).',
    'temperament.empathyBaseline': 'Moderate. He cares deeply about specific people (Grayparents, Praew) but struggles with broader empathy. Initially dismisses the Fourth Floor horrors as impossible (Ch12), is callous toward Praew\'s concerns (Ch13). His empathy is selective and slow to expand.',
    'temperament.dominanceVsDeference': 'Balanced. Defers to The Prime as a father figure but asserts dominance in other contexts (commands guards Ch15, confronts Godric). Uses his title strategically. Neither purely dominant nor submissive.',
    'temperament.adaptabilityVsRigidity': 'Moderate-rigid. Clings to his belief in The Prime despite mounting evidence (Ch12-14). "HE IS NOT AN ENEMY, PRAEW!" (Ch11). Slowly adapts but requires overwhelming proof. His worldview shifts are painful and reluctant.',

    'moralStructure.primaryDriver': 'Loyalty and leadership. He wants to protect those he loves through legitimate power. His arc moves from "trust the system" to "the system must be reformed." He chose Heir over Hunter because he believed he could do more good from within.',
    'moralStructure.moralRigidity': 'Moderate. He initially holds rigid loyalty to The Prime and the system ("And justice we will deliver"). But he slowly bends as evidence mounts. By Ch17, he commits treason to save Praew. His morality evolves but the shifts are wrenching.',
    'moralStructure.guiltSensitivity': 'Very high guilt. Guilt over his Grayparents starving (Ch8), guilt over failing Praew (Ch15-17), guilt over the woman killed by released prisoners (Ch17). "What have I done?" is his devastating realization. Guilt is his heaviest emotional burden.',
    'moralStructure.justificationTendency': 'Moderate. He initially justifies The Prime\'s actions and his own loyalty. "This wasn\'t betrayal. It was loyalty. Right?" (Ch13). He rationalizes to protect his worldview but eventually faces the truth. Less justification-prone than The Prime but more than Praew.',
  },
};
