import type { CharacterProfile } from '../types';

export const profile: CharacterProfile = {
  name: 'Mai / Mai Azadi',
  emotionalBaseline: {
    joy: 18,
    sadness: 17,
    anger: 15,
    fear: 13,
    disgust: 12,
    surprise: 10,
    trust: 20,
    anticipation: 13,
  },
  temperament: {
    patience: 45,
    impulsiveness: 40,
    confrontationalTendency: 55,
    agreeableness: 55,
    emotionalContainment: 60,
    riskAppetite: 60,
    curiosity: 50,
    prideSensitivity: 40,
    shameSensitivity: 55,
    empathyBaseline: 55,
    dominanceVsDeference: 45,
    adaptabilityVsRigidity: 60,
  },
  moralStructure: {
    primaryDriver: 'Human connection and loyalty to those who accept her; protecting the few people she is allowed to care about',
    moralRigidity: 35,
    guiltSensitivity: 45,
    justificationTendency: 40,
  },
  presentInChapters: [6, 7, 8, 9, 12, 13],
  reasoning: {
    'emotionalBaseline.joy': 'Moderate-high joy sensitivity. Mai presents constant cheerfulness: "Fun, right?" while teaching assassination (Ch6), claps and beams repeatedly, bounces on her heels (Ch9). Her joy is partly a survival mechanism ("I stay positive because if I don\'t... I would have killed myself" Ch7) but it\'s also genuine warmth.',
    'emotionalBaseline.sadness': 'Moderate sadness sensitivity. Cries when Praew rejects her friendship (Ch7): "tears ran down Mai\'s face." Her backstory reveals deep loss (family taken Ch13). But she suppresses sadness behind positivity. Her grief surfaces only when her defenses crack.',
    'emotionalBaseline.anger': 'Moderate anger sensitivity. Shows anger when Praew judges her: "What do you know?!" (Ch7). Flares when called out on her past. But anger is less dominant than for other characters — she\'s more hurt than furious. Her anger toward the guards who killed her family is cold and lethal, not hot.',
    'emotionalBaseline.fear': 'Moderate fear sensitivity. Terrified when Praew mentions the Fourth Floor: "her eyes were terrified" (Ch13). Admits she was "still pretty nervous" teaching her first class (Ch9). Her fear is situational — she fears losing the few people she has, not physical danger.',
    'emotionalBaseline.disgust': 'Low-moderate disgust sensitivity. She teaches arterial strikes "brightly" (Ch6), handles death clinically. Her upbringing on the Fourth Floor desensitized her to violence. She doesn\'t show disgust at blood or death, only at cruelty toward the innocent.',
    'emotionalBaseline.surprise': 'Low surprise sensitivity. She\'s trained to expect the unexpected. Praew\'s defiance surprises her briefly ("Mai Azadi hesitated" Ch6) but she recovers instantly. Very little truly catches her off guard.',
    'emotionalBaseline.trust': 'High trust sensitivity. She desperately wants to trust and be trusted. Earning one friend after five years of perfect kills (Ch7). She extends trust quickly to Praew and is devastated when rejected. "I\'ve decided, you can be my friend" (Ch6). Trust is her deepest need.',
    'emotionalBaseline.anticipation': 'Moderate. She anticipates social dynamics clumsily (reading a dating manual for friendship Ch9) but is less forward-planning than strategic characters. Her anticipation is emotional rather than tactical.',

    'temperament.patience': 'Moderate patience. She waited five years for the right to have a friend (Ch7). She gives Praew space after their argument per "the book" (Ch9). But she\'s also chatty and restless, filling silences compulsively, struggling to wait through social interactions.',
    'temperament.impulsiveness': 'Moderate. She reveals Godric\'s identity carelessly ("Oh well!" Ch6), shows up at Praew\'s house uninvited (Ch7), punches Praew during training without warning (Ch9). But in combat, she\'s calculated and precise — her impulsiveness is social, not tactical.',
    'temperament.confrontationalTendency': 'Moderate-high. She confronts Godric directly (Ch13), threatens students without hesitation (Ch6), stands between Praew and danger. But she avoids emotional confrontation — she deflects with humor rather than fighting when feelings are involved.',
    'temperament.agreeableness': 'Moderate-high. She desperately wants to please Praew, agrees to all of Praew\'s friendship rules (Ch9), adjusts her behavior when told it\'s uncomfortable. She\'s accommodating because she fears rejection, not because she\'s naturally submissive.',
    'temperament.emotionalContainment': 'Moderate-high. She masks immense trauma behind constant cheerfulness. "Her smile still fixed" while discussing murder (Ch6). Her containment is a survival strategy. But it breaks in key moments: crying about her family (Ch7), terror about the Fourth Floor (Ch13).',
    'temperament.riskAppetite': 'High risk appetite. Stabs Godric in the foot (Ch13), tells Praew classified information despite consequences, killed four guards as a child. She\'s willing to risk everything for those she cares about. Physical danger barely registers.',
    'temperament.curiosity': 'Moderate. She asks questions about friendship mechanics (Ch9), reads books to learn social skills. Her curiosity is directed at understanding human connection rather than mysteries or investigations.',
    'temperament.prideSensitivity': 'Low-moderate. She calls herself "the best assassin" (Ch7) but doesn\'t dwell on status. She\'s more concerned with acceptance than recognition. Being called a psychopath wounds her, but through rejection rather than pride.',
    'temperament.shameSensitivity': 'Moderate-high. She\'s ashamed of her social inadequacy: "Yeah, maybe I am sick" (Ch7). Reading a dating manual for friendship advice (Ch9) shows acute awareness of her deficiencies. She fears being seen as "not normal."',
    'temperament.empathyBaseline': 'Moderate-high. She saves Praew from having to kill (Ch6), fails her from the class to protect her conscience, trains her in silent movement to keep her safe. But empathy was suppressed by her training — it emerges selectively with those she\'s attached to.',
    'temperament.dominanceVsDeference': 'Balanced. She dominates in combat and classroom settings but defers to Praew socially. She follows The Prime\'s orders as an assassin. She\'s dominant when confident (combat) but submissive when insecure (friendship).',
    'temperament.adaptabilityVsRigidity': 'High adaptability. She adapts her teaching style, adjusts her behavior after Praew\'s criticism, shifts from formal instructor to friend seamlessly. Raised in brutal conditions, she learned to adapt or die. Her social flexibility is learned but genuine.',

    'moralStructure.primaryDriver': 'Connection. Mai kills because that\'s what she was shaped to do, but her driving motivation is human attachment. She earned the right to one friend and will do anything to keep that bond. Her moral compass follows the people she loves, not abstract principles.',
    'moralStructure.moralRigidity': 'Low moral rigidity. She operates in moral gray areas — killing is her job but she tries to minimize harm (saving Praew, explaining the victim\'s crimes Ch7). She doesn\'t have rigid rules; she navigates by loyalty and situational ethics.',
    'moralStructure.guiltSensitivity': 'Moderate guilt. She carries guilt about the lives she\'s taken, channeled into her forced positivity. "I stay positive because if I don\'t..." (Ch7). But she\'s also been conditioned to compartmentalize guilt. It surfaces when Praew forces her to confront it.',
    'moralStructure.justificationTendency': 'Moderate. She justifies her kills with context (the man killed his family Ch7) but doesn\'t build elaborate moral frameworks. She acknowledges the ugliness of what she does rather than fully rationalizing it. "You don\'t have to like what I do" (Ch7).',
  },
};
