import type { CharacterProfile } from '../types';

export const profile: CharacterProfile = {
  name: 'Praew',
  emotionalBaseline: {
    joy: 32,
    sadness: 40,
    anger: 32,
    fear: 27,
    disgust: 31,
    surprise: 23,
    trust: 36,
    anticipation: 32,
  },
  temperament: {
    patience: 25,
    impulsiveness: 65,
    confrontationalTendency: 60,
    agreeableness: 55,
    emotionalContainment: 25,
    riskAppetite: 65,
    curiosity: 70,
    prideSensitivity: 50,
    shameSensitivity: 40,
    empathyBaseline: 75,
    dominanceVsDeference: 55,
    adaptabilityVsRigidity: 65,
  },
  moralStructure: {
    primaryDriver: 'Protecting the innocent and those she cares about; justice for the oppressed',
    moralRigidity: 60,
    guiltSensitivity: 65,
    justificationTendency: 30,
  },
  presentInChapters: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18],
  reasoning: {
    'emotionalBaseline.joy': 'Praew laughs easily, teases Haldric, finds humor in adversity (Ch7 cafeteria banter, Ch10 Grayparents scene). She lights up rooms and her laughter "cut through the dull murmur of the cafeteria." High sensitivity to joy.',
    'emotionalBaseline.sadness': 'Cries multiple times: tears during the Hunter test stone exposure (Ch1), tears when hearing about Junya\'s parents (Ch6), tears when seeing the Fourth Floor child (Ch12), tears in the cell with Renwick (Ch15). Highly reactive to loss and suffering.',
    'emotionalBaseline.anger': 'Snaps at Wannii, curses in front of parents when seeing Mai (Ch7), confronts Mai aggressively with a dagger (Ch7), tells Godric off by calling him "Stone Face" (Ch4). Quick to anger but it burns hot and short.',
    'emotionalBaseline.fear': 'Moderate fear sensitivity. She feels fear (cell scene Ch15, embedding Ch16) but actively fights through it. When cornered by Mai she chooses defiance over cowering: "Then get it over with" (Ch6). Fear is present but doesn\'t paralyze her.',
    'emotionalBaseline.disgust': 'Strong disgust reactions to moral violations: seeing the Fourth Floor slavery (Ch12), Renwick\'s betrayal (Ch15), the scientist\'s behavior (Ch16). She physically nearly collapses seeing the child eat a Ratrod.',
    'emotionalBaseline.surprise': 'Moderate surprise sensitivity. Gets caught off guard (Mai being her instructor Ch6, Renwick\'s betrayal Ch15, The Prime saving then embedding her Ch16) but recovers quickly and adapts.',
    'emotionalBaseline.trust': 'High trust sensitivity - she trusts deeply and is wounded by betrayal. Trusts Haldric completely, extends trust to Mai despite initial conflict, trusts Note. When Asher betrayed them she was devastated (Ch1-2).',
    'emotionalBaseline.anticipation': 'Moderately high. She plans ahead (creating an excuse to meet Haldric Ch10), schemes to get Haldric to help Junya (Ch7), and is always looking toward the next step. But also acts impulsively.',

    'temperament.patience': 'Very low patience. Blurts out "Stone Face" without meaning to (Ch4), speaks before thinking repeatedly, interrupts, rushes into situations. "I just speak my mind and act on instinct. Then worry about the consequences later" (Ch6).',
    'temperament.impulsiveness': 'Highly impulsive. Grabs Mai\'s dagger and runs (Ch7), confronts Wannii mid-hallway (Ch8), agrees to meet a rebel (Ch11), runs toward Junya\'s cell (Ch12). Acts first, thinks later consistently.',
    'temperament.confrontationalTendency': 'Will confront anyone regardless of power: calls Godric "Stone Face" (Ch4), tells Mai to shut up while holding her own dagger (Ch7), confronts Wannii (Ch8), spits in the scientist\'s face (Ch16). Raises chin against threats.',
    'temperament.agreeableness': 'Moderate-high. She hugs Junya without hesitation (Ch6), comforts Bpen (Ch4), shows compassion to everyone. But she can be sharp and combative when pushed, lowering agreeableness somewhat.',
    'temperament.emotionalContainment': 'Very low containment. Cries openly, laughs loudly, curses in front of parents, blurts thoughts aloud. "I just speak my mind and act on instinct" (Ch6). Her emotions are always on display.',
    'temperament.riskAppetite': 'High risk appetite. Visits the Fourth Floor with a rebel (Ch12), agrees to meet Note (Ch11), confronts an assassin (Ch7), chooses death over killing an innocent (Ch6). Repeatedly chooses danger over safety.',
    'temperament.curiosity': 'Very high curiosity. Constantly investigates: the food shortage, Junya\'s parents, the Fourth Floor. "Could you please stop being so nosy?" Haldric begs (Ch7). Drives the entire investigation plotline.',
    'temperament.prideSensitivity': 'Moderate. She hates being seen as weak ("I will not use my height or gender as an excuse" Ch1), resents being considered clumsy. But she doesn\'t let pride prevent apologies (apologizes to Mai Ch9).',
    'temperament.shameSensitivity': 'Moderate-low. She embarrasses herself regularly (calling Godric Stone Face, falling during training Ch5) but recovers quickly: "Let them laugh. It\'ll be that much more satisfying when I\'m the first to pass" (Ch5).',
    'temperament.empathyBaseline': 'Maximum empathy. Hugs Junya instinctively (Ch6), comforts Bpen (Ch4), comforts Renwick despite his cruelty (Ch15), refuses to kill an innocent (Ch6). "If I were in your shoes, I\'d need one. So I gave you one" (Ch6). Empathy is her defining trait.',
    'temperament.dominanceVsDeference': 'Slightly dominant. She leads investigations, manipulates Haldric into helping (Ch7), confronts authority figures. But she defers to expertise (follows Mai\'s training, follows Godric\'s orders on the surface Ch18).',
    'temperament.adaptabilityVsRigidity': 'Highly adaptable. Pivots from hating Mai to befriending her (Ch7-9), adjusts her worldview as she learns truth (Ch12), survives the embedding by figuring out the trigger mechanism (Ch16). Learns silent movement despite being naturally clumsy.',

    'moralStructure.primaryDriver': 'Protection of the innocent is her core driver. She refuses to kill the bound man (Ch6), investigates for Junya\'s sake, feels guilt for failing her friends. "I\'d rather die than kill someone" (Ch7). Her moral compass points toward shielding the vulnerable.',
    'moralStructure.moralRigidity': 'Moderately rigid. She has firm lines (won\'t kill innocents) but she evolves: initially condemns Mai as a psychopath, then apologizes and befriends her. She\'s principled but capable of reassessing when presented with new evidence.',
    'moralStructure.guiltSensitivity': 'High guilt. Feels guilty about failing Junya and Wannii (Ch12, Ch15), guilty about judging Mai unfairly (Ch7), guilty about not protecting her friends. "I failed to protect Junya when she needed me most" (Ch15). Guilt is a persistent driver.',
    'moralStructure.justificationTendency': 'Low justification tendency. She doesn\'t rationalize her own failings. When she\'s wrong about Mai, she admits it. When Haldric calls her out, she "agreed with him" internally (Ch13). She faces her mistakes head-on rather than excusing them.',
  },
};
