import type { CharacterProfile } from '../types';

export const profile: CharacterProfile = {
  name: 'The Prime / Arthur Rivers',
  emotionalBaseline: {
    joy: 5,
    sadness: 13,
    anger: 18,
    fear: 17,
    disgust: 20,
    surprise: 5,
    trust: 7,
    anticipation: 17,
  },
  temperament: {
    patience: 65,
    impulsiveness: 15,
    confrontationalTendency: 35,
    agreeableness: 25,
    emotionalContainment: 70,
    riskAppetite: 45,
    curiosity: 35,
    prideSensitivity: 60,
    shameSensitivity: 30,
    empathyBaseline: 30,
    dominanceVsDeference: 70,
    adaptabilityVsRigidity: 35,
  },
  moralStructure: {
    primaryDriver: 'Survival of the human species at any cost; utilitarian calculus where the ends justify brutal means',
    moralRigidity: 70,
    guiltSensitivity: 35,
    justificationTendency: 75,
  },
  presentInChapters: [1, 2, 3, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
  reasoning: {
    'emotionalBaseline.joy': 'Very low joy sensitivity. Arthur rarely shows genuine happiness. His only moments of warmth are calculated: the paternal smile to Haldric (Ch11), the chuckle at Haldric\'s bluntness (Ch9). Even these feel measured and strategic. He lives under constant burden.',
    'emotionalBaseline.sadness': 'Moderate sadness sensitivity. Returns from his first Prime briefing visibly shaken, "bloodshot red" eyes, trembling hands (Ch3). Mourns what he\'s become: "who in their right mind would want to be the most hated man in the city?" (Ch11). But he buries grief quickly.',
    'emotionalBaseline.anger': 'Moderate-high anger sensitivity. Slams palm into stone table hard enough to indent it (Ch3). Kicks Haldric repeatedly (Ch18). "Blasted Hunters" escapes as a visceral slur (Ch9). His anger is controlled but when it breaks through, it\'s terrifying and physical.',
    'emotionalBaseline.fear': 'Moderate fear sensitivity. Returns "pale" and "shaking" after becoming Prime (Ch3). Fears Bresdin\'s escape (Ch18). Admits "I fear the story that begins with my end" (Ch17). His deepest fear is human extinction. But he masks fear behind stoicism.',
    'emotionalBaseline.disgust': 'High disgust sensitivity. Calls the scientist "absolutely deplorable" before killing him (Ch16). Sneers at Bresdin\'s rebellion, at Hunters\' independence, at weakness. "Blasted Hunters" carries genuine contempt. Moral disgust is a primary emotional driver.',
    'emotionalBaseline.surprise': 'Very low surprise sensitivity. Almost nothing catches him off guard. He anticipated Bresdin\'s escape (Ch10), knew Haldric was snooping (Ch13). The only genuine surprise is Godric\'s defection (Ch17-18). He plans for everything.',
    'emotionalBaseline.trust': 'Very low trust sensitivity. Trusts almost no one. Treats everyone as a potential threat or tool. Even Haldric is partly a strategic asset. His distrust stems from the burden of knowing Ravour\'s true state and the white-haired girl\'s manipulation.',
    'emotionalBaseline.anticipation': 'Moderate anticipation. He plans obsessively: the food shortage rationale, the embedding program, the portal search. "This must be the reason they insisted I reassign the task to Haldric. Just how far ahead can they predict?" (Ch10). Always thinking multiple steps ahead.',

    'temperament.patience': 'High patience. He endures years of being hated by the city, slowly builds the Noble Quarter, patiently explains his reasoning to Haldric across multiple chapters (Ch11, Ch14). Walks slowly and deliberately. "Every step measured, deliberate" (Ch14). But his patience has limits (the beating in Ch18).',
    'temperament.impulsiveness': 'Very low impulsiveness. Every action is calculated. He waits for Bresdin at the gate rather than blocking it (Ch10). Plans the embedding program over 14 years. "Each word sharpened before use" (Ch2). The rare impulsive moments (table slam Ch3, beating Ch18) reveal how much pressure he contains.',
    'temperament.confrontationalTendency': 'Low-moderate. Prefers manipulation and indirect control over direct confrontation. Uses Renwick as a proxy, lets Embedded warriors handle threats. When he confronts directly (killing the scientist Ch16), it\'s swift and decisive but he avoids it when possible.',
    'temperament.agreeableness': 'Low agreeableness. Refuses to compromise on the food shortage, the embedding program, or his authority. "I stopped talking and kept building" (Ch14). He doesn\'t seek approval or consensus. But he shows paternal softness with Haldric.',
    'temperament.emotionalContainment': 'Very high containment. His emotions slip only in extreme moments: the table indentation (Ch3), "Blasted Hunters" (Ch9), the beating of Haldric (Ch18). "In moments when anyone else might show a flicker of emotion, The Prime became as still and cold as stone" (Ch14). Master of composure.',
    'temperament.riskAppetite': 'Moderate. He takes calculated risks (the embedding program, choosing Haldric as Heir) but always with contingencies. He won\'t risk what he can\'t control. His risk-taking is strategic, never reckless.',
    'temperament.curiosity': 'Low-moderate. His curiosity is directed toward specific goals: the portals, the mural translations, the embedding research. He\'s not broadly curious but intensely focused on what serves his mission.',
    'temperament.prideSensitivity': 'High pride sensitivity. Takes personal offense at Godric\'s accusations (Ch9). "Lies spread like dye... a permanent mark on your reputation" (Ch14). The disconnect between his self-image as savior and public perception as tyrant clearly wounds him.',
    'temperament.shameSensitivity': 'Low shame sensitivity. He accepts being hated: "I would rather be despised than watch my people choke to death" (Ch14). He\'s hardened himself against public judgment. But Haldric\'s personal betrayal stings: "My fault for believing in you" (Ch13).',
    'temperament.empathyBaseline': 'Low empathy. He rationalizes enslaving the Fourth Floor, forcibly embedding people, and controlling minds through "necessity." He sees individuals as resources for species survival. His empathy flickers only with Haldric and in memories of young Asher.',
    'temperament.dominanceVsDeference': 'Highly dominant. Controls the entire city through surveillance, food rationing, hostage-keeping, and the recorrection program. Commands Renwick with voice alone and the boy obeys instantly (Ch17). Defers only to the white-haired girl, and that reluctantly.',
    'temperament.adaptabilityVsRigidity': 'Rigid. He has committed to a single path (embedding, portal search, species evacuation) and will not deviate. When challenged, he doubles down with more justification rather than reconsidering. His rigidity stems from genuine existential terror.',

    'moralStructure.primaryDriver': 'Species survival is his absolute moral north star. He will enslave, starve, torture, embed, and mind-control to prevent human extinction. "For the sake of our species, the risk must be taken" (Ch16). Everything is subordinate to this goal.',
    'moralStructure.moralRigidity': 'High moral rigidity. His utilitarian framework is ironclad. He\'s locked into "the ends justify the means" and won\'t accept alternatives. Even when Haldric offers simpler solutions (ration only children), he deflects rather than engage (Ch14).',
    'moralStructure.guiltSensitivity': 'Low-moderate guilt. He shows flickers: "I am sorry, but I must" (Ch17), the paternal gentleness with Haldric suggests some buried conscience. But he suppresses guilt with elaborate justifications. He\'s practiced at not feeling it.',
    'moralStructure.justificationTendency': 'Extremely high justification. Every atrocity has a rationalization: the food shortage prevents acclimation deaths (Ch14), the Noble Quarter is "gratitude not hostages" (Ch14), embedding is "necessity" (Ch16). He constructs airtight logical chains to defend every action.',
  },
};
