import type { ExtractedStimulant } from '../types';

export const stimulants: ExtractedStimulant[] = [
  // ===== Chapter 1 (chapterIndex: 1) =====
  {
    description: 'Asher faces the Hunter Test that will determine if his 12-year plan to escape his father succeeds — the anticipation of becoming a Hunter drives everything',
    eventType: 'obstacle',
    subject: 'self',
    source: 'world_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },
  {
    description: 'Asher struggles to put down the book "Srevlis" for the last time, honoring a pact with his friends to never read it again before the Hunter test',
    eventType: 'loss',
    subject: 'self',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },
  {
    description: 'Asher defends Praew against Renwick\'s sexist mockery, snapping his book shut and verbally lashing Renwick',
    eventType: 'moral_cue',
    subject: 'friend',
    source: 'enemy_caused',
    domain: 'morality',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },
  {
    description: 'Asher passes the knowledge portion of the Hunter exam, hearing his name called last among the six survivors',
    eventType: 'success',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },
  {
    description: 'Asher glances up at The Prime Archon watching from above and realizes the test is rigged so both he and Haldric will fail',
    eventType: 'betrayal',
    subject: 'family',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },
  {
    description: 'Asher hesitates at the ledge, then deliberately turns away from Haldric and takes both stones, betraying his best friend to pass the test',
    eventType: 'moral_cue',
    subject: 'friend',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },
  {
    description: 'Asher refuses to meet Haldric\'s furious gaze after stealing both stones, consumed by silent guilt',
    eventType: 'humiliation',
    subject: 'self',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 1,
  },

  // ===== Chapter 2 (chapterIndex: 2) =====
  {
    description: 'Asher steps through the gate to the surface for the first time — the culmination of everything he planned, facing the unknown world he dreamed of',
    eventType: 'success',
    subject: 'self',
    source: 'self_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher is announced as a Beast Hunter, the most prestigious role aside from Mythical Beast Hunter, triggering gasps across the hall',
    eventType: 'success',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher feels Haldric\'s blazing hatred radiating from him after the role announcements, knowing his friend despises him',
    eventType: 'rejection',
    subject: 'friend',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher turns his back on Praew and Haldric without saying goodbye or apologizing, walking away like a coward',
    eventType: 'separation',
    subject: 'friend',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher walks past The Prime and coldly accuses his father of trying to sabotage him by pitting him against his best friend',
    eventType: 'betrayal',
    subject: 'family',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Renwick taunts Asher with "all Rivers run cold," and Asher internally admits Renwick is right about his cruelty',
    eventType: 'insult',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'morality',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher silently apologizes to Haldric and Praew in his mind, clenching his fists with guilt while walking away',
    eventType: 'moral_cue',
    subject: 'friend',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Both Asher and Renwick are overwhelmed and blinded by the sun on their first surface exposure, crying and panicking',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher discovers the air on the surface is richer and thicker, coughing violently as his lungs burn from the unfamiliar sensation',
    eventType: 'obstacle',
    subject: 'self',
    source: 'world_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Asher meets his team lead Azel and is immediately embarrassed for speaking rudely to a superior',
    eventType: 'humiliation',
    subject: 'self',
    source: 'self_caused',
    domain: 'status',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },
  {
    description: 'Azel mocks Asher for crying and screaming during his first exposure to sunlight, revealing other Hunters watched as hazing tradition',
    eventType: 'humiliation',
    subject: 'self',
    source: 'ally_caused',
    domain: 'status',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 2,
  },

  // ===== Chapter 3 (chapterIndex: 3) =====
  {
    description: 'Asher nearly dies on his very first step on the surface when a BoltStone erupts where he stood; Azel yanks him back just in time',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Azel berates Asher for being distracted by the beauty of the surface, shattering his sense of awe',
    eventType: 'constraint',
    subject: 'self',
    source: 'ally_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Asher nearly draws his blade on a non-aggressive beast, almost getting both himself and Azel killed',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Asher reveals his surname Rivers and the team reacts with an unspoken, uncomfortable tension upon learning he is The Prime Archon\'s son',
    eventType: 'rejection',
    subject: 'self',
    source: 'world_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Asher learns beasts can be farmed and food shortage is manufactured, questioning everything he was taught',
    eventType: 'surprise_reveal',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Asher is given a shovel and told his Beast Hunter job is shoveling manure, realizing his father got the last laugh',
    eventType: 'humiliation',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Asher reflects on the flashback where his father forbade him from becoming a Hunter, remembering the original wound that drove his defiance',
    eventType: 'constraint',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Eight-year-old Asher is harshly told by his father never to call him "Father" in public again, and to only use "Prime Archon"',
    eventType: 'rejection',
    subject: 'family',
    source: 'authority_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Young Asher sees his father visibly shaken and terrified after becoming Prime, seeing a stone embedded in his chest, and is sworn to secrecy',
    eventType: 'surprise_reveal',
    subject: 'family',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Young Asher\'s father slams his palm so hard it dents a stone table when Asher says he\'d rather be a Hunter than end up like him',
    eventType: 'threat',
    subject: 'family',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Young Asher feels something crack inside him as his father demands to only be called Prime Archon, knowing the damage is permanent',
    eventType: 'loss',
    subject: 'family',
    source: 'authority_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
  {
    description: 'Young Asher is comforted by Praew and Haldric who mock the idea of being Prime Archon and invite him to become a Hunter with them instead',
    eventType: 'connection',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Asher',
    chapterIndex: 3,
  },
];
