import type { ExtractedStimulant } from '../types';

export const stimulants: ExtractedStimulant[] = [
  // ===== PROLOGUE (chapterIndex: 0) =====
  {
    description: 'Godric faces Boltrax alone at Stormhaven\'s gates knowing he will likely die, as no one else has the spine to stand',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Godric suppresses his fear before the battle, forcing himself to abandon the instinct that would not help when retreat is impossible',
    eventType: 'threat',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Boltrax strikes Godric with bone-crushing force, sending him flying into the gates and leaving him unable to reach his dropped spear',
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Godric drops his spear during combat and berates himself for the rookie mistake, believing he will not survive',
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'An eight-year-old boy (Srevlis) walks calmly toward the mythical beast, ignoring Godric\'s desperate orders to get back inside',
    eventType: 'surprise_reveal',
    subject: 'stranger',
    source: 'world_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Godric watches in awe as Srevlis fights with impossible mastery, wielding the spear as if born to it, surpassing anything Godric has ever seen',
    eventType: 'surprise_reveal',
    subject: 'stranger',
    source: 'world_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Guards drag Godric inside and slam the gates shut against his will, cutting him off from the fight and the boy',
    eventType: 'constraint',
    subject: 'self',
    source: 'ally_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Srevlis rejects Godric\'s offer of a home in Stormhaven and says "Do you think you\'re the only victim?" before disappearing into the storm',
    eventType: 'rejection',
    subject: 'stranger',
    source: 'world_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Godric is left humiliated by the realization that a wild-born eight-year-old did what he, a veteran Hunter, could not',
    eventType: 'humiliation',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Srevlis\'s words "Do you think you\'re the only victim?" gnaw at Godric, carving a permanent place in his mind and reminding him of his failure',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },
  {
    description: 'Godric finds renewed purpose from the encounter with Srevlis, recommitting to fight and protect others',
    eventType: 'moral_cue',
    subject: 'principle',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 0,
  },

  // ===== CHAPTER 4 (chapterIndex: 4) — as "Stone Face" / Professor Stone =====
  {
    description: 'Praew accidentally calls him "Stone Face" out loud in front of the whole class, prompting him to adopt the nickname as his title',
    eventType: 'insult',
    subject: 'self',
    source: 'ally_caused',
    domain: 'status',
    stakes: 0,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 4,
  },
  {
    description: 'Godric confronts the recruits about their failure at the Hunter test and tells them to get over it, channeling his own understanding of purpose and second chances',
    eventType: 'moral_cue',
    subject: 'group',
    source: 'self_caused',
    domain: 'morality',
    stakes: 1,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 4,
  },

  // ===== CHAPTER 6 (chapterIndex: 6) =====
  {
    description: 'Mai reveals to the students that their instructor "Stone Face" is actually Silverwing Godric, the Mythical Beast Hunter, against his wishes',
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'ally_caused',
    domain: 'autonomy',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 6,
  },

  // ===== CHAPTER 8 (chapterIndex: 8) =====
  {
    description: 'Godric reveals his three territory marks (Boltrax wing, Tarnox horns, bite mark) to the class, exposing his deeply personal battle scars',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 8,
  },
  {
    description: 'Students look at Godric with hero worship after seeing his marks, and he snaps at them that there is no glory in death',
    eventType: 'moral_cue',
    subject: 'group',
    source: 'self_caused',
    domain: 'morality',
    stakes: 1,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 8,
  },
  {
    description: 'Godric overhears Praew and Wannii arguing about the investigation near a government facility and warns them with a veiled threat about letting stones slip',
    eventType: 'danger_cue',
    subject: 'group',
    source: 'self_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 1,
    certainty: 1,
    targetCharacter: 'Godric',
    chapterIndex: 8,
  },

  // ===== CHAPTER 9 (chapterIndex: 9) =====
  {
    description: 'Godric is unusually agitated and grouchy in class, stomping and slamming his fist on the desk, hinting at internal turmoil after his confrontation with The Prime',
    eventType: 'obstacle',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 9,
  },
  {
    description: 'Godric confronts The Prime Archon in a furious argument, shouting about what The Prime is "doing to them" and threatening him',
    eventType: 'injustice',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 9,
  },
  {
    description: 'Godric storms out of The Prime\'s office with clenched fists, visibly disheveled, after the confrontation fails to resolve his concerns',
    eventType: 'failure',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 9,
  },

  // ===== CHAPTER 13 (chapterIndex: 13) =====
  {
    description: 'Mai reveals Godric\'s former title "Madman Godric, the Deadly Scientist" from the Ghost operatives, striking a deeply personal nerve',
    eventType: 'insult',
    subject: 'self',
    source: 'ally_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 13,
  },
  {
    description: 'Godric threatens Mai for calling him by his former Ghost title, showing his sensitivity about his past as a scientist',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 13,
  },
  {
    description: 'Praew tells Godric he was one of her heroes, using past tense, showing she has lost faith in him',
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 13,
  },
  {
    description: 'Mai stabs a dagger through Godric\'s foot when he takes his eyes off her during the confrontation',
    eventType: 'harm',
    subject: 'self',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 13,
  },
  {
    description: 'Godric discovers that his students (Wannii, Junya, Jorpen) have been disappearing and he cannot find them, leading him to search the Fourth Floor',
    eventType: 'loss',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 13,
  },

  // ===== CHAPTER 15 (chapterIndex: 15) =====
  {
    description: 'Godric finds classified medical records show he was injured (dislocated shoulder, impaled foot) in "combat training" — evidence of his fight with Mai',
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 1,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 15,
  },

  // ===== CHAPTER 16 (chapterIndex: 16) =====
  {
    description: 'Godric reveals he has been searching for the missing students and heard screaming from below the Fourth Floor, confirming a hidden Fifth Floor',
    eventType: 'danger_cue',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 16,
  },
  {
    description: 'Godric admits the deadliest person in the city (Mai) was put into a coma by an unknown attacker, and he does not know who did it',
    eventType: 'surprise_reveal',
    subject: 'friend',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 1,
    certainty: 1,
    targetCharacter: 'Godric',
    chapterIndex: 16,
  },
  {
    description: 'Haldric confronts Godric with a surged ForceStone demanding to know where Praew is, forcing Godric into a fight with an ally',
    eventType: 'threat',
    subject: 'self',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 16,
  },

  // ===== CHAPTER 17 (chapterIndex: 17) =====
  {
    description: 'Godric and Haldric discover Praew strapped to a slab with a stone embedded in her chest, bloodied and barely conscious, confirming The Prime\'s atrocities',
    eventType: 'injustice',
    subject: 'friend',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 17,
  },
  {
    description: 'Godric sees two dead bodies (including Junya) in The Prime\'s recorrection chamber — his own students murdered in experiments',
    eventType: 'loss',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 17,
  },
  {
    description: 'Godric recognizes that his missing students Wannii and Jorpen are among the six masked Embedded warriors he must fight, turned into mind-controlled soldiers',
    eventType: 'betrayal',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 17,
  },

  // ===== CHAPTER 18 (chapterIndex: 18) =====
  {
    description: 'Godric calls The Prime "brother" as he says goodbye, acknowledging the personal betrayal of fighting his own sibling',
    eventType: 'separation',
    subject: 'family',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'The Prime shouts that Godric will be hunted to the ends of the world for taking Praew, threatening his life and freedom',
    eventType: 'threat',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Praew quotes his own book back to him — "Thank you for picking up your spear to face the storm!" — validating his lifelong purpose',
    eventType: 'connection',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric faces six Embedded warriors alone to buy Praew time to escape, knowing he will likely die',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric is forced to decapitate his own students Wannii and Jorpen, who have been turned into mindless Embedded warriors',
    eventType: 'moral_cue',
    subject: 'group',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric prays for his students\' mercy in their next life before killing them, revealing deep moral anguish',
    eventType: 'loss',
    subject: 'group',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Renwick slashes Godric\'s throat from behind after the battle, leaving him bleeding out',
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric\'s ribs shatter from a surged strike during the battle, and his body is failing from multiple wounds and surge overuse',
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric collapses at the gate after the battle, driving his spear into the ground one final time as the world dims around him',
    eventType: 'loss',
    subject: 'self',
    source: 'self_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric worries that Praew will view her own compassion as weakness if the Embedded warriors track her down using her empathy against her',
    eventType: 'moral_cue',
    subject: 'friend',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 1,
    certainty: 1,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric acknowledges his "greatest shame" — the burn mark on the back of his neck — connecting him to the recorrection program that enslaved his students',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
  {
    description: 'Godric reflects that he and his brother (The Prime) share the same weakness — growing more callous while growing more calloused',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Godric',
    chapterIndex: 18,
  },
];
