import type { ExtractedStimulant } from '../types';

export const stimulants: ExtractedStimulant[] = [
  // === CHAPTER 1 (chapterIndex: 1) ===
  {
    description: "Haldric performs the triangle hand gesture with Praew and Asher, reaffirming their unbreakable bond before the test.",
    eventType: 'connection',
    subject: 'friend',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 1,
  },
  {
    description: "Asher hesitates and then abandons Haldric dangling over a pit during the practical test, choosing to take both stones.",
    eventType: 'betrayal',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 1,
  },
  {
    description: "Haldric screams that it's not fair as the Hunter dismisses his protest, leaving him shaking with barely contained rage.",
    eventType: 'injustice',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 1,
  },

  // === CHAPTER 2 (chapterIndex: 2) ===
  {
    description: "Haldric is assigned to government administration in the Prime Archon's office, not a poor job but not the Hunter role he wanted.",
    eventType: 'constraint',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 2,
  },
  {
    description: "Asher is named Beast Hunter, the most prestigious role, while Haldric is left with a desk job, intensifying his fury.",
    eventType: 'injustice',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 2,
  },
  {
    description: "Asher walks away without saying goodbye or apologizing, completing his betrayal of Haldric and Praew.",
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 2,
  },

  // === CHAPTER 7 (chapterIndex: 7) — Praew visits Haldric at ration station ===
  {
    description: "Haldric sees how small his food rations are compared to Praew's, a visible sign of the city's inequitable food distribution.",
    eventType: 'injustice',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 7,
  },
  {
    description: "Praew asks Haldric to help investigate the suspicious disappearance of Junya's parents, pulling him into a risky mission.",
    eventType: 'moral_cue',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 7,
  },

  // === CHAPTER 8 (chapterIndex: 8) ===
  {
    description: "Haldric discovers his Grayparents have been secretly skipping meals to save food for him, leaving them gaunt and weak.",
    eventType: 'surprise_reveal',
    subject: 'family',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 8,
  },
  {
    description: "Haldric tells his Grayparents he cannot lose them too after already losing his parents, feeling desperate fear for their health.",
    eventType: 'threat',
    subject: 'family',
    source: 'world_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 8,
  },

  // === CHAPTER 9 (chapterIndex: 9) ===
  {
    description: "Haldric overhears Godric furiously confronting The Prime about something involving 'them,' sparking his suspicion.",
    eventType: 'surprise_reveal',
    subject: 'authority',
    source: 'world_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 2,
    certainty: 1,
    targetCharacter: 'Haldric',
    chapterIndex: 9,
  },
  {
    description: "Haldric accidentally asks The Prime if he is okay, revealing he overheard the argument and compromising his position.",
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 9,
  },
  {
    description: "The Prime apologizes for Asher's betrayal during the test and shows unexpected vulnerability, confusing Haldric's view of him.",
    eventType: 'connection',
    subject: 'authority',
    source: 'authority_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 9,
  },
  {
    description: "Haldric feels the thrill of the hunt for the first time since starting his desk job, reignited by the mysteries around the Prime.",
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 9,
  },

  // === CHAPTER 10 (chapterIndex: 10) ===
  {
    description: "Haldric is assigned to personally deliver the retirement notice to War Claw Bresdin, a Mythical Beast Hunter.",
    eventType: 'obstacle',
    subject: 'self',
    source: 'authority_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 10,
  },
  {
    description: "Hunters at the office threaten and shove Haldric when he announces the honorable discharge of their legend.",
    eventType: 'threat',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 10,
  },
  {
    description: "Bresdin flees and opens the surface gate to blind Haldric, then attacks him with a weapon while Haldric is unable to see.",
    eventType: 'danger_cue',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 10,
  },
  {
    description: "Haldric successfully fights Bresdin while blind using childhood training, and The Prime intervenes to stop the Hunter.",
    eventType: 'success',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 10,
  },
  {
    description: "The Prime Archon checks Haldric for injuries with paternal concern, and praises his fighting ability.",
    eventType: 'reward',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 10,
  },

  // === CHAPTER 11 (chapterIndex: 11) ===
  {
    description: "Haldric's body has acclimated to the surface, gaining enhanced strength, stamina, and senses overnight.",
    eventType: 'success',
    subject: 'self',
    source: 'world_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "The Prime tells Haldric that it should have been him who became a Hunter, acknowledging the injustice of the test.",
    eventType: 'reward',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "The Prime tells Haldric he is fired, causing a moment of panic before Haldric realizes it may be a joke leading to something bigger.",
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'authority_caused',
    domain: 'future_security',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "Haldric sees the surface for the first time in full beauty but turns away, choosing to stay and serve rather than become a Hunter.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "The Prime Archon publicly announces Haldric as the Heir Archon, his chosen successor, shocking the entire administration.",
    eventType: 'success',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "The administration erupts in cheers for Haldric and he feels belonging for the first time in the building.",
    eventType: 'connection',
    subject: 'group',
    source: 'world_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "The Prime gives Haldric the Master Key and the book of the previous Archon, entrusting him with the city's deepest secrets.",
    eventType: 'reward',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "A mysterious white-haired girl appears to Haldric that no one else can see, speaking to him and then vanishing through a door.",
    eventType: 'surprise_reveal',
    subject: 'stranger',
    source: 'world_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "Praew confronts Haldric about his new power and The Prime, urging him to use his position to uncover the truth.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },
  {
    description: "Haldric accidentally smashes a stone table with his fist while defending The Prime, revealing his new strength to Praew.",
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 11,
  },

  // === CHAPTER 12 (chapterIndex: 12) ===
  {
    description: "Haldric witnesses the Fourth Floor's slavery, whippings, and horrific conditions, shattering his image of The Prime as a benevolent leader.",
    eventType: 'injustice',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 12,
  },
  {
    description: "Haldric desperately insists The Prime doesn't know about the Fourth Floor atrocities, his voice cracking as denial battles with what he has witnessed.",
    eventType: 'obstacle',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 12,
  },
  {
    description: "Haldric steals two Sifaralith stones and a ledger from the Fourth Floor identification area, committing a dangerous act of rebellion.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 12,
  },

  // === CHAPTER 13 (chapterIndex: 13) ===
  {
    description: "Note reveals he is a rebel and accuses The Prime of holding Hunter families hostage, further eroding Haldric's trust.",
    eventType: 'surprise_reveal',
    subject: 'authority',
    source: 'enemy_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 13,
  },
  {
    description: "Haldric realizes being seen with a rebel could get his entire family executed, and he panics about Praew's recklessness.",
    eventType: 'threat',
    subject: 'family',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 13,
  },
  {
    description: "Haldric hurts Praew with his enhanced grip and cruelly insults her intelligence, then watches her walk away without looking back.",
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 13,
  },
  {
    description: "Haldric breaks into The Prime's office and discovers the BoltStone Recorrection Program documents signed by Godric, and breeding ledgers proving the food shortage is manufactured.",
    eventType: 'surprise_reveal',
    subject: 'authority',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 13,
  },
  {
    description: "The Prime catches Haldric snooping in his office with classified documents exposed, expressing deep disappointment.",
    eventType: 'humiliation',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 13,
  },

  // === CHAPTER 14 (chapterIndex: 14) ===
  {
    description: "The Prime takes Haldric to the Noble Quarter and systematically dismantles his assumptions about the upper class being pampered.",
    eventType: 'surprise_reveal',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 14,
  },
  {
    description: "The Prime reveals the planet Ravour is dying and that everyone must eventually acclimate to survive evacuation through portals.",
    eventType: 'threat',
    subject: 'group',
    source: 'authority_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 14,
  },
  {
    description: "The Prime reveals the ten Beasts of Legend have learned to reproduce, potentially spelling human extinction.",
    eventType: 'danger_cue',
    subject: 'group',
    source: 'authority_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 14,
  },
  {
    description: "The mysterious white-haired girl reappears on the surface, getting terrifyingly close to Haldric and whispering that he looks like someone.",
    eventType: 'danger_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'safety',
    stakes: 1,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 14,
  },
  {
    description: "The Prime tells Haldric the world needs a kind heart willing to risk everything, and that he chose Haldric for that quality.",
    eventType: 'reward',
    subject: 'self',
    source: 'authority_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 14,
  },

  // === CHAPTER 15 (chapterIndex: 15) ===
  {
    description: "Haldric realizes Praew was right about The Prime and is consumed by guilt for how he treated her, resolving to apologize.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 15,
  },
  {
    description: "Praew's parents reveal she has been missing since yesterday and no one can find her, sending Haldric into a panic.",
    eventType: 'danger_cue',
    subject: 'friend',
    source: 'world_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 15,
  },
  {
    description: "Haldric finds classified medical records showing Godric was injured in suspicious late-night combat and another patient is redacted and in a coma.",
    eventType: 'surprise_reveal',
    subject: 'authority',
    source: 'self_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 15,
  },
  {
    description: "Haldric confronts Godric in the training center, attacks him with surged ForceStone, and is easily defeated and thrown into a wall.",
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 15,
  },

  // === CHAPTER 16 (chapterIndex: 16) ===
  {
    description: "Godric reveals he did not kidnap Praew's friends but has been trying to find them, and that he heard screaming below the Fourth Floor.",
    eventType: 'surprise_reveal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 16,
  },
  {
    description: "Haldric realizes the entrance to the Fifth Floor is hidden in The Prime's own office, confirming The Prime's involvement.",
    eventType: 'surprise_reveal',
    subject: 'authority',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 16,
  },

  // === CHAPTER 17 (chapterIndex: 17) ===
  {
    description: "Haldric sees Praew strapped to a slab, covered in blood with a stone embedded in her chest, and two dead bodies nearby.",
    eventType: 'harm',
    subject: 'friend',
    source: 'authority_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 17,
  },
  {
    description: "Haldric blames himself for believing The Prime's lies instead of trusting Praew, realizing his denial may have cost lives.",
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 17,
  },
  {
    description: "Haldric confesses to Godric that he loves Praew, knowing he may never see her again after the rescue.",
    eventType: 'separation',
    subject: 'friend',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Haldric',
    chapterIndex: 17,
  },
  {
    description: "Haldric uses the Master Key to release every prisoner in the city jail as a distraction, an act of treason to save Praew.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 17,
  },
  {
    description: "A freed prisoner murders a woman in front of her child as a direct consequence of Haldric's jailbreak, devastating him with guilt.",
    eventType: 'harm',
    subject: 'stranger',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 17,
  },

  // === CHAPTER 18 (chapterIndex: 18) ===
  {
    description: "The Prime Archon beats Haldric with kicks and backhands, calling him a fool who doomed everyone.",
    eventType: 'harm',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 18,
  },
  {
    description: "Haldric involuntarily calls The Prime 'Father' while being beaten, revealing his deep conflicted attachment despite everything.",
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 18,
  },
  {
    description: "The Prime immediately softens after being called Father, asking if Haldric is alright, creating a whiplash of conflicting emotions.",
    eventType: 'connection',
    subject: 'authority',
    source: 'authority_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Haldric',
    chapterIndex: 18,
  },
];
