import type { ExtractedStimulant } from '../types';

export const stimulants: ExtractedStimulant[] = [
  // ===== CHAPTER 6 (chapterIndex: 6) — Mai's first appearance as Ghost Operations instructor =====
  {
    description: 'Mai poisons all students with needles during a flicker of darkness to establish authority and test their composure on her first day as instructor',
    eventType: 'threat',
    subject: 'group',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Bpen challenges Mai\'s authority by calling assassination cowardly and questioning her age, forcing her to assert dominance with a second poison needle',
    eventType: 'insult',
    subject: 'self',
    source: 'ally_caused',
    domain: 'status',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Mai kills the bound man in front of Praew after Praew refuses to do it, performing the execution to save Praew\'s life despite Praew\'s moral condemnation',
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Mai hesitates when Praew defiantly tells her to "get it over with" rather than cower, revealing a flurry of conflicting emotions breaking through her mask',
    eventType: 'surprise_reveal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Mai acknowledges the trauma of what her students went through, admitting the worst beasts she ever fought were human, revealing her own haunted past',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Mai accidentally reveals Godric\'s true identity as Silverwing Godric to her class despite being told not to, showing her difficulty with secrets',
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Mai fails Praew from Ghost Operations class to protect her from having to kill again, and tells Praew she has earned her respect',
    eventType: 'connection',
    subject: 'friend',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },
  {
    description: 'Praew dismisses Mai coldly after class with "Can I go now?" leaving Mai sounding dejected after her attempt at friendship',
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 6,
  },

  // ===== CHAPTER 7 (chapterIndex: 7) — Mai visits Praew's home =====
  {
    description: 'Mai follows Praew home and shows up uninvited at her parents\' house, sitting casually with them despite being a trained assassin',
    eventType: 'connection',
    subject: 'friend',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },
  {
    description: 'Praew calls Mai a "psychopathic murderer" and says she would never be friends with her, telling her to stay away from her parents',
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },
  {
    description: 'Mai breaks down crying and reveals she is Stormhaven\'s best assassin only because she was raised to kill, not because she enjoys it',
    eventType: 'humiliation',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },
  {
    description: 'Mai reveals she was only allowed to make a single friend after five years of maintaining a flawless kill record, and Praew is the first person she chose',
    eventType: 'connection',
    subject: 'friend',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },
  {
    description: 'Mai reveals she would have killed herself long ago if not for staying positive, exposing the depth of her suffering and isolation',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },
  {
    description: 'Mai reveals the man she killed was a cannibal who murdered and ate his own wife and daughter, defending her actions against Praew\'s moral judgment',
    eventType: 'injustice',
    subject: 'self',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },
  {
    description: 'Mai confronts Praew with "You condemn me but protect people like that?" before walking away, devastated by the injustice of being judged',
    eventType: 'injustice',
    subject: 'self',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 7,
  },

  // ===== CHAPTER 9 (chapterIndex: 9) — Mai and Praew reconcile =====
  {
    description: 'Praew returns to apologize to Mai, admitting she was wrong and offering to try being friends with boundaries',
    eventType: 'connection',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Mai',
    chapterIndex: 9,
  },
  {
    description: 'Mai anxiously asks if Praew is going to "break up" with her, revealing how much their friendship means and how fragile it feels to her',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 2,
    certainty: 1,
    targetCharacter: 'Mai',
    chapterIndex: 9,
  },
  {
    description: 'Mai reveals she has been studying a romance guide book to learn how friendships work, not even knowing the difference between courting and friendship',
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 9,
  },
  {
    description: 'Mai tries to painfully force a reassuring smile when Praew performs poorly, her eye twitching as she struggles to express unfamiliar empathy',
    eventType: 'obstacle',
    subject: 'self',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Mai',
    chapterIndex: 9,
  },
  {
    description: 'When Praew asks Mai to train her the way she was trained, Mai reflexively punches her, revealing her traumatic upbringing through instinct',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 9,
  },

  // ===== CHAPTER 13 (chapterIndex: 13) =====
  {
    description: 'Mai learns about the Fourth Floor from Praew, and her eyes glaze over with terror as she relives traumatic memories of growing up there',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai grabs Praew and desperately begs her to never return to the Fourth Floor, her eyes wide with genuine terror',
    eventType: 'danger_cue',
    subject: 'friend',
    source: 'self_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai reveals she was born on the Fourth Floor and her entire family worked in the Sifaralith Identification Program',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai reveals her two older brothers blamed her for their father\'s death, saying she should never have been born',
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai recounts her mother losing all her fingers in a stone accident and the family being sentenced to disposal, the moment that destroyed her childhood',
    eventType: 'loss',
    subject: 'family',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai watches her mother and two brothers being dragged away by guards and never sees them again',
    eventType: 'separation',
    subject: 'family',
    source: 'authority_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai is struck by a guard so hard she flies into a pile of stones and blacks out during the struggle for her family',
    eventType: 'harm',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai hunts down and kills the three guards who took her family, slitting their throats and stabbing through the last one\'s foot in an act of vengeance',
    eventType: 'success',
    subject: 'self',
    source: 'self_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'The previous Prime Archon watches Mai kill the guards with amusement instead of stopping her, then recruits her into Ghost Operations',
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Godric confronts Mai about revealing Fourth Floor secrets to Praew and calls her behavior "sick" for imitating a young person to experience missed youth',
    eventType: 'insult',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Godric accuses Mai of making Praew her "next victim" and threatens her for committing treason by sharing classified information',
    eventType: 'threat',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Praew declares Mai her best friend and says she doesn\'t care about Mai\'s age, validating their bond in the face of Godric\'s hostility',
    eventType: 'connection',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai stabs Godric through the foot and shouts for Praew to run, sacrificing her own safety to protect her friend',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Godric casually kicks Mai across the training hall like a child\'s toy, demonstrating the massive power gap between them',
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },
  {
    description: 'Mai reveals she does not age due to something that happened on the Fourth Floor, exposing her deepest secret and isolation',
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 13,
  },

  // ===== CHAPTER 16 (chapterIndex: 16) =====
  {
    description: 'Godric reveals that the deadliest person in the city (Mai) has been put into a coma by an unknown attacker — Mai is incapacitated and unable to help',
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Mai',
    chapterIndex: 16,
  },
];
