import type { ExtractedStimulant } from '../types';

export const stimulants: ExtractedStimulant[] = [
  // === PROLOGUE (chapterIndex: 0) ===
  {
    description: "Praew reads the story of Srevlis and feels her heart race with excitement and emotional attachment to the tale that raised her.",
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'attachment',
    stakes: 0,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 0,
  },

  // === CHAPTER 1 (chapterIndex: 1) ===
  {
    description: "Praew closes the book for the last time as part of a pact with her friends, saying goodbye to the story that raised her.",
    eventType: 'separation',
    subject: 'self',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Praew feels tense and anxious in the waiting hall before the Hunter Test, doubting herself and spiraling with negative thoughts.",
    eventType: 'threat',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 3,
    certainty: 1,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Praew catches herself using her height and gender as excuses and angrily refuses to accept them as reasons for potential failure.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Renwick mocks Praew for being emotional about the book and says women should not be Hunters.",
    eventType: 'insult',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'status',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Haldric and Asher perform their triangle hand gesture and recite their bond phrase, giving Praew reassurance before her test.",
    eventType: 'connection',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "During the knowledge exam, a mysterious red-glowing stone overwhelms Praew with alien emotions: alarm, fear, hatred, longing, sadness, and defiance.",
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'world_caused',
    domain: 'safety',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Praew watches Asher abandon Haldric during the practical test, choosing to take both stones instead of helping his friend.",
    eventType: 'betrayal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Renwick sexually harasses Praew during the practical test, causing her to hesitate and stumble, losing the competition.",
    eventType: 'humiliation',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },
  {
    description: "Praew fails the Hunter Test permanently with no second chances, losing her lifelong dream.",
    eventType: 'failure',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 1,
  },

  // === CHAPTER 2 (chapterIndex: 2) ===
  {
    description: "Praew is assigned to Special Forces under the constable, an unexpectedly good position that surprises her.",
    eventType: 'success',
    subject: 'self',
    source: 'authority_caused',
    domain: 'future_security',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 2,
  },
  {
    description: "Praew watches Haldric shake with rage as Asher is named Beast Hunter, feeling the tension between her friends.",
    eventType: 'danger_cue',
    subject: 'friend',
    source: 'authority_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 2,
  },
  {
    description: "Asher leaves without saying goodbye or apologizing, turning his back on Praew and Haldric.",
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 2,
  },
  {
    description: "Renwick makes a vulgar parting comment telling Praew to keep his bed warm, humiliating her publicly.",
    eventType: 'insult',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'status',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 2,
  },

  // === CHAPTER 4 (chapterIndex: 4) ===
  {
    description: "Praew accidentally calls her drill instructor 'Stone Face' out loud, embarrassing herself in front of the class.",
    eventType: 'humiliation',
    subject: 'self',
    source: 'self_caused',
    domain: 'status',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 4,
  },
  {
    description: "Professor Stone tells the recruits they were given a second chance and could still go to the surface, reigniting Praew's buried hope.",
    eventType: 'reward',
    subject: 'self',
    source: 'authority_caused',
    domain: 'future_security',
    stakes: 2,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 4,
  },
  {
    description: "Praew worries about her parents' declining health and reduced rations, realizing the food shortage is worsening for them.",
    eventType: 'threat',
    subject: 'family',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 4,
  },
  {
    description: "Praew kneels on her bed and traces the carved words from her parents, feeling grateful for their sacrifices.",
    eventType: 'reminder_cue',
    subject: 'family',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 4,
  },

  // === CHAPTER 5 (chapterIndex: 5) ===
  {
    description: "Praew reads the terrifying silent course test rules including water crossing with BoltStones and wonders if this is a death sentence.",
    eventType: 'threat',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 5,
  },
  {
    description: "Praew trips and falls during the silent movement practice in front of her classmates, who barely contain their laughter.",
    eventType: 'humiliation',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 5,
  },

  // === CHAPTER 6 (chapterIndex: 6) ===
  {
    description: "Mai Azadi poisons the entire class with needles through their ears as an opening lesson in assassination.",
    eventType: 'danger_cue',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 6,
  },
  {
    description: "Praew is ordered to kill a bound, begging man and refuses, choosing death over murder.",
    eventType: 'moral_cue',
    subject: 'principle',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 6,
  },
  {
    description: "Mai slits the bound man's throat in front of Praew, spraying blood on her face.",
    eventType: 'harm',
    subject: 'stranger',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 6,
  },
  {
    description: "Mai fails Praew from Ghost Operations class, meaning she must now pass both remaining classes or face reassignment.",
    eventType: 'constraint',
    subject: 'self',
    source: 'ally_caused',
    domain: 'future_security',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 6,
  },

  // === CHAPTER 7 (chapterIndex: 7) ===
  {
    description: "Junya tells Praew about her parents' suspicious disappearance from the mines, pulling Praew into a dangerous investigation.",
    eventType: 'moral_cue',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 7,
  },
  {
    description: "Praew notices her own parents growing weaker and too tired to fuss over her, realizing the food shortage is taking a toll.",
    eventType: 'threat',
    subject: 'family',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 7,
  },
  {
    description: "Mai Azadi appears at Praew's home uninvited, sitting with her parents while armed with a dagger, terrifying Praew.",
    eventType: 'danger_cue',
    subject: 'family',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 7,
  },
  {
    description: "Praew harshly rejects Mai's friendship and calls her a psychopathic murderer, later feeling deep guilt about it.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 7,
  },
  {
    description: "Mai reveals the bound man was a cannibal who murdered and ate his wife and daughter, shattering Praew's moral certainty.",
    eventType: 'surprise_reveal',
    subject: 'principle',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 7,
  },

  // === CHAPTER 8 (chapterIndex: 8) ===
  {
    description: "Wannii confronts Praew for endangering Junya by sharing her investigation with someone in the Prime's office.",
    eventType: 'rejection',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 8,
  },
  {
    description: "Wannii reveals she deliberately failed the Hunter test to stay with Junya, making Praew realize the depth of their bond and her own recklessness.",
    eventType: 'surprise_reveal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'morality',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 8,
  },
  {
    description: "Godric catches Praew and Wannii arguing about classified matters near a government facility and ominously warns about people going missing.",
    eventType: 'threat',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 8,
  },

  // === CHAPTER 9 (chapterIndex: 9) ===
  {
    description: "Praew apologizes to Mai and they reconcile, forming a genuine friendship with agreed-upon boundaries.",
    eventType: 'connection',
    subject: 'friend',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 9,
  },
  {
    description: "Praew learns Junya and Wannii are missing after failing to show up to class, realizing they may have acted on their dangerous plan.",
    eventType: 'danger_cue',
    subject: 'friend',
    source: 'world_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 9,
  },

  // === CHAPTER 10 (chapterIndex: 10) ===
  {
    description: "Praew teases Haldric's grandparents into thinking they are dating, creating a cover story for their secret meetings.",
    eventType: 'success',
    subject: 'self',
    source: 'self_caused',
    domain: 'autonomy',
    stakes: 0,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 10,
  },

  // === CHAPTER 12 (chapterIndex: 12) ===
  {
    description: "Praew witnesses the Fourth Floor: enslaved people being whipped, children eating raw Ratrods, and horrific conditions.",
    eventType: 'injustice',
    subject: 'group',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 12,
  },
  {
    description: "Praew recognizes her missing classmate Jorpen working as an enforcer-slave in the Fourth Floor identification program.",
    eventType: 'surprise_reveal',
    subject: 'friend',
    source: 'authority_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 12,
  },
  {
    description: "Note reveals that Junya's parents were likely murdered for discovering the Fourth Floor, and that Junya and Wannii may also be dead.",
    eventType: 'loss',
    subject: 'friend',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 12,
  },

  // === CHAPTER 13 (chapterIndex: 13) ===
  {
    description: "Haldric grabs Praew's wrist with inhuman strength, hurting her and revealing he has been hiding his acclimation from her.",
    eventType: 'betrayal',
    subject: 'self',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 13,
  },
  {
    description: "Haldric cruelly tells Praew she is not as smart as she pretends to be and that she belongs in Special Forces, not Administration.",
    eventType: 'insult',
    subject: 'self',
    source: 'ally_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 13,
  },
  {
    description: "Mai reveals she was born on the Fourth Floor, her family was destroyed, and she does not age, deepening the bond and shocking Praew.",
    eventType: 'surprise_reveal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 13,
  },
  {
    description: "Godric arrives and threatens Mai; Mai stabs his foot and tells Praew to run, forcing Praew to flee in fear for both their lives.",
    eventType: 'danger_cue',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 13,
  },
  {
    description: "A mysterious attacker intercepts Praew just before she reaches Haldric's home, and she is captured.",
    eventType: 'harm',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 13,
  },

  // === CHAPTER 15 (chapterIndex: 15) ===
  {
    description: "Praew wakes up imprisoned in a narrow, abrasive cell with no way out, struggling to breathe.",
    eventType: 'constraint',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 15,
  },
  {
    description: "Renwick reveals himself as her captor and jailer, having feigned being a fellow prisoner to manipulate her emotions.",
    eventType: 'betrayal',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 15,
  },
  {
    description: "Praew discovers Wannii's burnt, bloated corpse in her shared cell with Junya.",
    eventType: 'loss',
    subject: 'friend',
    source: 'enemy_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 15,
  },
  {
    description: "Junya is dragged away screaming by the guard while Praew fails to hold onto her, losing her grip on Junya's bracelet.",
    eventType: 'separation',
    subject: 'friend',
    source: 'enemy_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 15,
  },
  {
    description: "Praew accepts she cannot save her friends and puts on Junya's bracelet as a reminder of her failure to protect them.",
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 15,
  },

  // === CHAPTER 16 (chapterIndex: 16) ===
  {
    description: "Praew sees Junya dead on a stone slab with a Sifaralith embedded in her skull.",
    eventType: 'loss',
    subject: 'friend',
    source: 'enemy_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 16,
  },
  {
    description: "The scientist grabs Praew's hair and invades her personal space while she is strapped down, making her feel violated and powerless.",
    eventType: 'humiliation',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 16,
  },
  {
    description: "The Prime Archon kills the scientist but then reveals he will not release Praew and instead begins the embedding process.",
    eventType: 'betrayal',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 16,
  },
  {
    description: "The Prime slams a Mythical BoltStone into Praew's chest, causing agonizing pain as electricity tears through her body.",
    eventType: 'harm',
    subject: 'self',
    source: 'authority_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 16,
  },
  {
    description: "Praew realizes the Hunter Test was actually a screening to find people compatible with rare stones, reframing her entire life.",
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 16,
  },
  {
    description: "Praew survives the Mythical BoltStone embedding by figuring out the trigger is sound and silently enduring the agony.",
    eventType: 'success',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 16,
  },

  // === CHAPTER 17 (chapterIndex: 17) ===
  {
    description: "The Prime begins the BoltStone recorrection program on Praew, using pulses to make her mind impressionable against her will.",
    eventType: 'constraint',
    subject: 'self',
    source: 'authority_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 17,
  },
  {
    description: "Praew experiences a vision of her parents telling her to leave the city and go on her adventure, giving her emotional comfort.",
    eventType: 'connection',
    subject: 'family',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 17,
  },

  // === CHAPTER 18 (chapterIndex: 18) ===
  {
    description: "Praew wakes to find Godric has rescued her from The Prime and is taking her to the surface to escape.",
    eventType: 'reward',
    subject: 'self',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 18,
  },
  {
    description: "Renwick and six Embedded warriors block the final gate to the surface, threatening to end her escape.",
    eventType: 'obstacle',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 18,
  },
  {
    description: "Godric sacrifices himself to hold back the warriors so Praew can escape, and she realizes she may never see her hero again.",
    eventType: 'separation',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 18,
  },
  {
    description: "Praew runs across the deadly surface alone, triggering dangerous stones and suffering electricity from her own BoltStone, nearly dying.",
    eventType: 'danger_cue',
    subject: 'self',
    source: 'world_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'Praew',
    chapterIndex: 18,
  },
  {
    description: "Praew accepts her likely death on the surface with a smile, finding peace in dying free rather than as a prisoner.",
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'autonomy',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'Praew',
    chapterIndex: 18,
  },
];
