import type { ExtractedStimulant } from '../types';

export const stimulants: ExtractedStimulant[] = [
  // ===== Chapter 1 (chapterIndex: 1) =====
  {
    description: 'The Prime Archon watches from above as his son Asher betrays his best friend Haldric during the Hunter test, a scenario The Prime himself orchestrated',
    eventType: 'moral_cue',
    subject: 'family',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 1,
  },

  // ===== Chapter 2 (chapterIndex: 2) =====
  {
    description: 'The Prime tries to speak to Asher before he leaves and is coldly cut off as Asher walks right past him, refusing any fatherly connection',
    eventType: 'rejection',
    subject: 'family',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 2,
  },
  {
    description: 'Asher publicly accuses The Prime of sabotaging his Hunter test by pitting him against his best friend',
    eventType: 'insult',
    subject: 'family',
    source: 'ally_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 2,
  },
  {
    description: 'The Prime sputters and fails to find words as Asher walks away, left speechless by his son\'s rejection',
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 2,
  },
  {
    description: 'Renwick makes a veiled, suspicious comment about "a prime contribution" that alarms Arthur, but Renwick deflects before Arthur can press further',
    eventType: 'danger_cue',
    subject: 'stranger',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 1,
    immediacy: 2,
    certainty: 1,
    targetCharacter: 'The Prime',
    chapterIndex: 2,
  },

  // ===== Chapter 3 (chapterIndex: 3) — Flashback: Arthur becomes Prime =====
  {
    description: 'Arthur learns the previous Prime has died and he must immediately assume the title, receiving the news while children play nearby',
    eventType: 'loss',
    subject: 'authority',
    source: 'world_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },
  {
    description: 'Arthur learns a mythical beast threatens Stormhaven and the only willing defender, Godric, has already gone to the surface to likely die',
    eventType: 'threat',
    subject: 'group',
    source: 'world_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 2,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },
  {
    description: 'Newly-made Prime Arthur is visibly shaken, sweating, bloodshot-eyed and terrified after learning the secrets shown only to the Prime Archon',
    eventType: 'surprise_reveal',
    subject: 'self',
    source: 'authority_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },
  {
    description: 'Arthur harshly tells young Asher to never call him "Father" in public again, squeezing his arm hard enough to hurt, terrified of public vulnerability',
    eventType: 'constraint',
    subject: 'family',
    source: 'self_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },
  {
    description: 'Young Asher calls Arthur a coward hiding underground while real heroes sacrifice themselves, directly challenging his honor',
    eventType: 'insult',
    subject: 'family',
    source: 'ally_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },
  {
    description: 'Arthur slams the stone table so hard he leaves a permanent palm print, losing control of his enhanced strength in front of Asher',
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },
  {
    description: 'Arthur forbids Asher from becoming a Hunter, declaring it too dangerous, but Asher reminds him the law prevents the Prime from blocking the test',
    eventType: 'constraint',
    subject: 'family',
    source: 'ally_caused',
    domain: 'autonomy',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 3,
  },

  // ===== Chapter 9 (chapterIndex: 9) =====
  {
    description: 'Godric storms into The Prime\'s office furious, screaming accusations about what Arthur is doing to people, physically confronting him',
    eventType: 'threat',
    subject: 'authority',
    source: 'ally_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 9,
  },
  {
    description: 'After Godric leaves, The Prime mutters "blasted Hunters" with open disdain before catching himself, revealing a rare crack in his composure',
    eventType: 'failure',
    subject: 'self',
    source: 'self_caused',
    domain: 'competence',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 9,
  },
  {
    description: 'Haldric unexpectedly asks "Are you okay?" after overhearing the confrontation, and The Prime is moved that someone cares about his wellbeing',
    eventType: 'connection',
    subject: 'stranger',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 1,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 9,
  },
  {
    description: 'The Prime admits that Haldric may be the first person to worry about his wellbeing since he became Prime, revealing deep loneliness',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 9,
  },
  {
    description: 'The Prime apologizes to Haldric for Asher\'s betrayal during the test, admitting it was not supposed to happen that way',
    eventType: 'moral_cue',
    subject: 'family',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 9,
  },

  // ===== Chapter 10 (chapterIndex: 10) =====
  {
    description: 'The Prime orchestrates the capture of rebel Bresdin by letting Haldric unknowingly serve as bait, then cuts off Bresdin\'s hand with a sword',
    eventType: 'threat',
    subject: 'authority',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 10,
  },
  {
    description: 'Arthur feels satisfaction watching Hunters admire Haldric, but also disgust, recognizing Haldric as the bridge Asher was supposed to be',
    eventType: 'reminder_cue',
    subject: 'family',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 10,
  },

  // ===== Chapter 11 (chapterIndex: 11) =====
  {
    description: 'The Prime reveals to Haldric that he doesn\'t know where he went wrong with Asher, admitting his son had everything and threw it away to be a Hunter',
    eventType: 'loss',
    subject: 'family',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 11,
  },
  {
    description: 'The Prime tells Haldric "it should have been you" as a Hunter, implicitly acknowledging Asher\'s failure and his own parenting failure',
    eventType: 'failure',
    subject: 'family',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 11,
  },
  {
    description: 'The Prime names Haldric as Heir Archon, publicly choosing someone else\'s child over his own son as his successor',
    eventType: 'moral_cue',
    subject: 'family',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 11,
  },

  // ===== Chapter 13 (chapterIndex: 13) =====
  {
    description: 'The Prime catches Haldric snooping in his office looking through classified documents, feeling deep disappointment at the betrayal of trust',
    eventType: 'betrayal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 13,
  },
  {
    description: 'The Prime tells Haldric "My fault for believing in you," expressing that even his chosen successor has turned against him',
    eventType: 'rejection',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'belonging',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 13,
  },
  {
    description: 'The Prime laments that the whole city blames him for everything and he thought Haldric would be different, revealing his isolation',
    eventType: 'injustice',
    subject: 'self',
    source: 'world_caused',
    domain: 'belonging',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 13,
  },

  // ===== Chapter 14 (chapterIndex: 14) =====
  {
    description: 'The Prime walks with heavy, exhausted strides when no one of importance is watching, revealing the burden of carrying the city alone',
    eventType: 'reminder_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'autonomy',
    stakes: 1,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The Prime flushes with rage when the Noble Quarter\'s original meaning is twisted by rumors into a sign of privilege and corruption',
    eventType: 'injustice',
    subject: 'self',
    source: 'world_caused',
    domain: 'status',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The Prime reveals Ravour is dying and acclimation is getting harder each year, confessing the species faces extinction',
    eventType: 'threat',
    subject: 'group',
    source: 'world_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The Prime reveals the noble beasts have learned to reproduce, meaning ten have become eleven, an existential threat he cannot stop',
    eventType: 'danger_cue',
    subject: 'group',
    source: 'world_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The Prime admits he has tried to form alliances with other cities to find the portals but they either don\'t believe him or suspect invasion',
    eventType: 'failure',
    subject: 'group',
    source: 'world_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The Prime confronts the white-haired phantom girl, telling her he will never forgive her and that they are not allies',
    eventType: 'moral_cue',
    subject: 'stranger',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 2,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The phantom girl accuses The Prime of lying by omission to Haldric, cutting through his justifications',
    eventType: 'insult',
    subject: 'self',
    source: 'enemy_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 2,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },
  {
    description: 'The Prime confesses "The world needs you, Haldric. It needs a kind heart. I will not suffice," admitting his own moral insufficiency',
    eventType: 'moral_cue',
    subject: 'self',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 1,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 14,
  },

  // ===== Chapter 16 (chapterIndex: 16) =====
  {
    description: 'The Prime kills the sadistic scientist who was torturing Praew, stabbing a sword through his throat with visible disgust',
    eventType: 'moral_cue',
    subject: 'stranger',
    source: 'self_caused',
    domain: 'morality',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 16,
  },
  {
    description: 'The Prime\'s hands tremble with awe as he sees the Mythical BoltStone successfully embed into Praew, whispering "Finally, after fourteen years"',
    eventType: 'success',
    subject: 'group',
    source: 'self_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 16,
  },
  {
    description: 'Praew begs The Prime not to use the recorrection program on her, asking "Why must everything be decided for me?" as he overrides her will',
    eventType: 'moral_cue',
    subject: 'stranger',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 16,
  },

  // ===== Chapter 17 (chapterIndex: 17) =====
  {
    description: 'Renwick draws a sword on The Prime after witnessing the embedding, but The Prime uses a voice command to force Renwick to stand down and obey',
    eventType: 'threat',
    subject: 'stranger',
    source: 'enemy_caused',
    domain: 'safety',
    stakes: 2,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 17,
  },
  {
    description: 'The Prime warns that Renwick has "doomed us all" by threatening him instead of supporting the embedding that could save the species',
    eventType: 'danger_cue',
    subject: 'group',
    source: 'ally_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 2,
    certainty: 2,
    targetCharacter: 'The Prime',
    chapterIndex: 17,
  },
  {
    description: 'Haldric releases every prisoner in the city jail as a distraction, causing chaos, murder, and destruction throughout Stormhaven',
    eventType: 'betrayal',
    subject: 'friend',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 17,
  },

  // ===== Chapter 18 (chapterIndex: 18) =====
  {
    description: 'Godric ties up The Prime and rescues Praew, calling it a crime punishable by death while The Prime is helpless on the floor',
    eventType: 'humiliation',
    subject: 'self',
    source: 'ally_caused',
    domain: 'status',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
  {
    description: 'The Prime screams at Godric to bring Praew back, threatening to hunt him to the ends of the world, losing all composure',
    eventType: 'loss',
    subject: 'group',
    source: 'ally_caused',
    domain: 'future_security',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
  {
    description: 'Godric says "Goodbye, brother" as he takes Praew away, severing his familial bond with Arthur permanently',
    eventType: 'separation',
    subject: 'family',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
  {
    description: 'The Prime beats Haldric viciously, kicking him repeatedly on the floor, screaming "You doomed us all" and "Why must you ruin everything?"',
    eventType: 'harm',
    subject: 'friend',
    source: 'self_caused',
    domain: 'morality',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
  {
    description: 'The Prime learns that Haldric freed Bresdin, his most dangerous enemy, causing Arthur visible fear for the first time',
    eventType: 'danger_cue',
    subject: 'self',
    source: 'ally_caused',
    domain: 'safety',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
  {
    description: 'Haldric calls out "Father, please!" to stop The Prime from kicking him, and Arthur freezes, momentarily confronted with the parental bond he craves',
    eventType: 'reminder_cue',
    subject: 'family',
    source: 'ally_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
  {
    description: 'The Prime must imprison his own brother Godric as a result of the night\'s events, losing his last remaining familial ally',
    eventType: 'loss',
    subject: 'family',
    source: 'self_caused',
    domain: 'attachment',
    stakes: 3,
    immediacy: 3,
    certainty: 3,
    targetCharacter: 'The Prime',
    chapterIndex: 18,
  },
];
